name: Deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: vignesh-demo   # set this to your application's name
  PYTHON_VERSION: '3.9'               # set this to the Python version to use
  STARTUP_COMMAND: 'gunicorn -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 main:app'

on:
  workflow_dispatch:
    inputs:
      artifact_id:
        description: "Artifact ID to process"
        required: true
        type: string
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_id }}
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          #startup-command: ${{ env.STARTUP_COMMAND }}

      - name: Send Notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "🚀 Deployment completed successfully!"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
